# Generated by Django 3.2.18 on 2023-03-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_auto_20230328_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='delete',
        ),
        migrations.AddField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('Creada', 'Opcion 1'), ('En ejecución', 'Opcion 2'), ('Completado', 'Opcion 3')], default='Creada', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
