# Generated by Django 3.2.18 on 2023-03-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_auto_20230322_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(default='Tarea por hacer'),
            preserve_default=False,
        ),
    ]
