# Generated by Django 3.2.18 on 2023-03-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_auto_20230328_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='delete',
            new_name='delete_user',
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('Creada', 'Option 1'), ('En ejecución', 'Option 2'), ('Completado', 'Option 3')], default='Creada', max_length=20),
        ),
    ]
