# Generated by Django 3.2.18 on 2023-03-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_auto_20230329_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('Creado', 'C'), ('En proceso', 'P'), ('Terminado', 'T')], default='Creado', max_length=15),
        ),
    ]
